---
title: "Lab 8 - Linear Regression in R"
author: "Robert Saldivar"
date: "November 20, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Loading Tidyverese and data file

library(tidyverse)
salmon <- read_csv("salmon_imports.csv")
```

```{r}
# Creating Exploratory Scatterplot

salmon_scatter <- ggplot(salmon, aes(x=year, y=salmon_fresh)) +
  geom_point()
salmon_scatter

#overall there appears to be a relationship between the year and the salmon imports. There are some years that do not meet the expectation of the relationship.

```

```{r}
#Linear Regression

salmon_model <- lm(salmon_fresh ~ year, data = salmon)
salmon_model

#model equation y=7550x-14982940 or imports(tons)=7550(year)-14982940

#the slope in the context of this model means that for every increase in year there is approximately an increase of 7550 tons of salmon imported

# The Y intercept means that at "year 0" there was -14982920 tons of salmon being imported. That is concerning because that is impossible for a variety of reasons. That means it is not possible to extrapolate data into the past.
```

```{r}
#Model Diagnostics

par(mfrow = c(2,2))
salmon_model_plot <- plot(salmon_model)
salmon_model_plot

#The residuals appear to be normally distrubuted
#There does not appear to be any concern of hertoscedasticity or any major outliers
```
```{r}
#Explore model fit and significance

summary(salmon_model)

#this model can significanly predict salmon imports by the year
#R^2 is a measure to predict how well the model can predict the outcome of dependent variable(salmon imports) by the independent variable(year)
#The proportion of salmon imports that cannot be explained by year is 0.0522
```

```{r}
#Prepare a final graph

salmon_final_graph <- ggplot(salmon, aes(x=year, y=salmon_fresh)) +
  geom_point() +
  geom_smooth(method = lm, se = TRUE, size = 0.5, color = "grey20") +
  theme_bw() +
  scale_x_continuous(expand = c(0,0), limits = c(1990, 2017)) +
  labs(x = "Year", y = "U.S. Annual Fresh Salmon Imports\n(1,000 pounds)")

salmon_final_graph
```

```{r}
#Making predictions using the model

new_years <- data.frame(year = c(2022, 2024, 2026, 2028))

future_predict <- predict(salmon_model, newdata = new_years, interval = "confidence")
future_predict

predictions <- data.frame(new_years, future_predict)
predictions
```

```{r}
#Finding Pearson's r(correlation)

salmon_correlation <- cor.test(salmon$year, salmon$salmon_fresh)
salmon_correlation

#There is a strong positive correlation between the year and salmon imported
```

